language: ruby
rvm:
  - 2.3.1
services:
  - redis-server
cache: bundler
sudo: false
addons:
  postgresql: '9.4'
env:
  - DATABASE_URL=postgresql://postgres@localhost/one_quran_test?pool=5
before_script:
  - bundle exec rails db:drop
  - bundle exec rails db:create
  - bundle exec rails db:migrate
install: bundle install --local --jobs=3 --retry=3 --deployment --path=vendor/bundle
